# Generated by Django 6.0.1 on 2026-01-26 16:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tên sách')),
                ('author', models.CharField(max_length=100, verbose_name='Tác giả')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Số lượng trong kho')),
                ('image', models.ImageField(blank=True, null=True, upload_to='books/', verbose_name='Ảnh bìa')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Danh mục')),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='ISBN')),
                ('publisher', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nhà xuất bản')),
                ('publication_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Năm xuất bản')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Sách',
                'verbose_name_plural': 'Sách',
                'db_table': 'books',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Họ tên')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=128, verbose_name='Mật khẩu')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Địa chỉ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng ký')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Khách hàng',
                'verbose_name_plural': 'Khách hàng',
                'db_table': 'customers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(max_length=100, verbose_name='Phương thức thanh toán')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
            ],
            options={
                'verbose_name': 'Phương thức thanh toán',
                'verbose_name_plural': 'Phương thức thanh toán',
                'db_table': 'payment_methods',
                'ordering': ['method_name'],
            },
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(max_length=100, verbose_name='Phương thức giao hàng')),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Phí giao hàng')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('estimated_days', models.PositiveIntegerField(default=3, verbose_name='Số ngày dự kiến')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
            ],
            options={
                'verbose_name': 'Phương thức giao hàng',
                'verbose_name_plural': 'Phương thức giao hàng',
                'db_table': 'shipping_methods',
                'ordering': ['fee'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Họ tên')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=128, verbose_name='Mật khẩu')),
                ('role', models.CharField(choices=[('admin', 'Quản trị viên'), ('staff', 'Nhân viên')], default='staff', max_length=20, verbose_name='Vai trò')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
            ],
            options={
                'verbose_name': 'Nhân viên',
                'verbose_name_plural': 'Nhân viên',
                'db_table': 'staff',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='store.customer', verbose_name='Khách hàng')),
            ],
            options={
                'verbose_name': 'Giỏ hàng',
                'verbose_name_plural': 'Giỏ hàng',
                'db_table': 'carts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tổng tiền')),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Phí giao hàng')),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('confirmed', 'Đã xác nhận'), ('shipping', 'Đang giao hàng'), ('delivered', 'Đã giao hàng'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('shipping_address', models.TextField(verbose_name='Địa chỉ giao hàng')),
                ('shipping_phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đặt hàng')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='store.customer', verbose_name='Khách hàng')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='store.payment', verbose_name='Phương thức thanh toán')),
                ('shipping', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='store.shipping', verbose_name='Phương thức giao hàng')),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Đơn hàng',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Số lượng')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá tại thời điểm mua')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='store.book', verbose_name='Sách')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order', verbose_name='Đơn hàng')),
            ],
            options={
                'verbose_name': 'Sản phẩm trong đơn hàng',
                'verbose_name_plural': 'Sản phẩm trong đơn hàng',
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Số lượng')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày thêm')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='store.book', verbose_name='Sách')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.cart', verbose_name='Giỏ hàng')),
            ],
            options={
                'verbose_name': 'Sản phẩm trong giỏ',
                'verbose_name_plural': 'Sản phẩm trong giỏ',
                'db_table': 'cart_items',
                'unique_together': {('cart', 'book')},
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Điểm đánh giá')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Bình luận')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đánh giá')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='store.book', verbose_name='Sách')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='store.customer', verbose_name='Khách hàng')),
            ],
            options={
                'verbose_name': 'Đánh giá',
                'verbose_name_plural': 'Đánh giá',
                'db_table': 'ratings',
                'ordering': ['-created_at'],
                'unique_together': {('customer', 'book')},
            },
        ),
    ]
